FROM tepickering/iraf-community-base:latest

MAINTAINER T. E. Pickering "te.pickering@gmail.com"

ARG USER_ID
ARG GROUP_ID

RUN groupadd -f -g ${GROUP_ID} iraf && \
    useradd -l -u ${USER_ID} -g iraf iraf

RUN mkdir -p /home/iraf && chown -R iraf:iraf /home/iraf

USER iraf
ENV HOME /home/iraf
