#!/bin/bash

# this script wraps the running of iraf within its container and sets up the X windows configuration so
# the graphics windows work properly. it maps the current working directory into the container as /home/iraf/data
# and runs 'xgterm -e cl' there. if you want to switch to a different directory on the host, you'll need to exit
# and then rerun this script there.

xhost + 127.0.0.1 > /dev/null 2>&1

docker run -ti --rm \
    -e DISPLAY=host.docker.internal:0 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $PWD:/home/iraf/data \
    --sysctl net.ipv4.tcp_keepalive_intvl=45 \
    --sysctl net.ipv4.tcp_keepalive_probes=15 \
    --sysctl net.ipv4.tcp_keepalive_time=120 \
    iraf:latest \
    /bin/bash -c "\
        cd /home/iraf; \
        source .bashrc; \
        conda activate iraf27; \
        cd data; \
        if [ ! -e login.cl ]
        then
            cp ../login.cl .
            mkdir uparm
        fi; \
        pyraf \
    "

xhost - 127.0.0.1 > /dev/null 2>&1
